name: Update CLI

on:
  schedule:
  - cron: "14 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Check out documentation branch
      uses: actions/checkout@v2
      with:
        ref: 'dist'
        path: 'public'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install npm packages
      run: npm install
    - name: Fetch latest documentation
      run: node cli/cli_fetch.js
    - name: Clean up old documentation
      run: rm -rf content/cli
    - name: Import documentation
      run: node cli/cli_import.js
    - name: Check for changes
      id: status
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "::set-output name=has_changes::1"
        fi
    - name: Check in source updates
      if: steps.status.outputs.has_changes == '1'
      run: |
        git add --verbose .
        git config user.name 'CI User'
        git config user.email 'noreply@npmjs.com'
        git commit -m 'CLI documentation update from CI'
    - name: Build documentation
      run: npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push source changes
      if: steps.status.outputs.has_changes == '1'
      run: git push origin main
    - name: Check for changes to docs
      id: docs-status
      working-directory: public
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "::set-output name=has_changes::1"
        fi
    - name: Publish documentation
      if: steps.docs-status.outputs.has_changes == '1'
      working-directory: public
      run: |
        git add --verbose .
        git config user.name 'CI User'
        git config user.email 'noreply@npmjs.com'
        git commit -m 'CLI documentation update from CI'
        git push origin dist
